import { getStore } from '@netlify/blobs';
import { googleMapsURL, parseGooglePlace } from '../../lib/google-maps';
const encoder=new TextEncoder(), decoder=new TextDecoder(), DAY=60*60*24, COOKIE='dhaiqati_session';
type Entry={id:string;name:string;area:string;category:string;date:string;rating:number;notes:string;lat:number;lng:number;photos:string[];googleMapsUrl:string;createdAt:string};
const journalStore=()=>getStore('dhaiqati-journals'), photoStore=()=>getStore('dhaiqati-photos');
const bytes=(s:string)=>encoder.encode(s); const b64=(v:Uint8Array)=>Buffer.from(v).toString('base64url'); const unb64=(v:string)=>new Uint8Array(Buffer.from(v,'base64url'));
async function sign(value:string){const key=await crypto.subtle.importKey('raw',bytes(process.env.SESSION_SECRET??''),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,bytes(value)))}
function cookie(req:Request){return req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1)}
async function user(req:Request){const token=cookie(req), name=process.env.ADMIN_USERNAME; if(!token||!name||!(process.env.SESSION_SECRET??'').length)return null; const [body,sig,extra]=token.split('.');if(!body||!sig||extra)return null; const a=unb64(sig),b=await sign(body);if(a.length!==b.length||a.some((v,i)=>v!==b[i]))return null;try{const s=JSON.parse(decoder.decode(unb64(body)));return s.sub===name&&s.exp>Date.now()/1000?name:null}catch{return null}}
function out(data:unknown,status=200,headers:Record<string,string>={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store',...headers}})}
async function login(req:Request){let body:any;try{body=await req.json()}catch{return out({error:'تعذّر قراءة بيانات الدخول.'},400)}; if(!process.env.ADMIN_USERNAME||!process.env.ADMIN_PASSWORD||!(process.env.SESSION_SECRET??'').length)return out({error:'إعداد تسجيل الدخول غير مكتمل.'},503);if(body.username!==process.env.ADMIN_USERNAME||body.password!==process.env.ADMIN_PASSWORD)return out({error:'اسم المستخدم أو كلمة المرور غير صحيحة.'},401);const payload=b64(bytes(JSON.stringify({sub:body.username,exp:Math.floor(Date.now()/1000)+30*DAY}))),token=`${payload}.${b64(await sign(payload))}`;return out({authenticated:true},200,{'Set-Cookie':`${COOKIE}=${token}; Path=/; Max-Age=${30*DAY}; HttpOnly; Secure; SameSite=Lax`})}
function valid(d:any):Entry|Response{const s=(k:string,n:number,required=false)=>typeof d[k]==='string'&&d[k].length<=n&&(!required||d[k].trim())?d[k].trim():null; const name=s('name',100,true),area=s('area',150),category=s('category',40,true),date=s('date',10,true),notes=s('notes',5000),url=d.googleMapsUrl??'';if(!name||area===null||!category||!date||notes===null||typeof d.id!=='string'||!/^[\w-]{10,80}$/.test(d.id)||!Number.isInteger(d.rating)||d.rating<0||d.rating>5||!Number.isFinite(d.lat)||Math.abs(d.lat)>85||!Number.isFinite(d.lng)||Math.abs(d.lng)>180||!Array.isArray(d.photos)||d.photos.length>6||typeof url!=='string'||url.length>4096||(url&&!googleMapsURL(url)))return out({error:'راجع الحقول المطلوبة وطول النص.'},400);return {id:d.id,name,area,category,date,rating:d.rating,notes,lat:d.lat,lng:d.lng,photos:d.photos,googleMapsUrl:url,createdAt:new Date().toISOString()}}
async function journal(owner:string){return ((await journalStore().get(`journals/${owner}`,{type:'json'}))??{entries:[]}) as {entries:Entry[]}}
async function handler(req:Request){const path=new URL(req.url).pathname, owner=await user(req);if(path==='/api/auth/login'&&req.method==='POST')return login(req);if(path==='/api/auth/logout'&&req.method==='POST')return out({signedOut:true},200,{'Set-Cookie':`${COOKIE}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax`});if(path==='/api/auth/me')return owner?out({authenticated:true}):out({error:'سجّل الدخول.'},401);if(!owner)return out({error:'انتهت جلسة الدخول. سجّل الدخول مرة أخرى.'},401);if(path==='/api/entries'&&req.method==='GET')return out(await journal(owner));if(path==='/api/entries'&&req.method==='POST'){const d=valid(await req.json());if(d instanceof Response)return d;const j=await journal(owner);j.entries=[d,...j.entries.filter(x=>x.id!==d.id)].sort((a,b)=>b.date.localeCompare(a.date));await journalStore().setJSON(`journals/${owner}`,j);return out({entry:d})}if(path.startsWith('/api/entries/')&&req.method==='DELETE'){const id=path.slice(13),j=await journal(owner),entry=j.entries.find(x=>x.id===id);if(!entry)return out({error:'التجربة غير موجودة.'},404);j.entries=j.entries.filter(x=>x.id!==id);await journalStore().setJSON(`journals/${owner}`,j);await Promise.all(entry.photos.map(id=>photoStore().delete(`${owner}/${id}`)));return out({deleted:true})}if(path==='/api/photos'&&req.method==='POST'){const form=await req.formData(),file=form.get('photo');if(!(file instanceof File)||!file.size||file.size>8*1024*1024)return out({error:'اختر صورة صالحة بحجم لا يتجاوز ٨ ميغابايت.'},400);const id=crypto.randomUUID();await photoStore().set(`${owner}/${id}`,file,{metadata:{type:file.type}});return out({url:'/api/photos/'+id},201)}if(path.startsWith('/api/photos/')&&req.method==='GET'){const id=path.slice(12),item=await photoStore().getWithMetadata(`${owner}/${id}`,{type:'blob'});return item?new Response(item.data,{headers:{'Content-Type':String(item.metadata.type??'image/jpeg'),'Cache-Control':'private, max-age=3600'}}):out({error:'الصورة غير موجودة.'},404)}if(path==='/api/maps/resolve'&&req.method==='POST'){const input=(await req.json()).url;let url=typeof input==='string'?googleMapsURL(input.trim()):null;if(!url)return out({error:'استخدم رابط مشاركة من قوقل ماب فقط.'},400);for(let i=0;i<6;i++){const place=parseGooglePlace(url.href);if(place.position)return out(place);if(!['maps.app.goo.gl','goo.gl'].includes(url.hostname))break;const r=await fetch(url.href,{redirect:'manual',signal:AbortSignal.timeout(8000)});const l=r.headers.get('location');await r.body?.cancel();if(!l||r.status<300||r.status>=400)break;url=googleMapsURL(new URL(l,url).href);if(!url)break}return out({error:'تعذّر قراءة موقع المطعم من الرابط.'},422)}return out({error:'غير موجود.'},404)}
export const config={path:'/api/*'};export default handler;
